# Configuração do banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}

# Configuração do JWT
api.security.token.secret=${JWT_SECRET}

# Configuração do servidor
server.port=${SERVER_PORT}
server.address=${SERVER_ADDRESS}
